/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author PcRa
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDMenu = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMIGesttionCompras = new javax.swing.JMenuItem();
        jMICompraxprov = new javax.swing.JMenuItem();
        jMICompraxFecha = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JDMenu.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout JDMenuLayout = new javax.swing.GroupLayout(JDMenu);
        JDMenu.setLayout(JDMenuLayout);
        JDMenuLayout.setHorizontalGroup(
            JDMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        JDMenuLayout.setVerticalGroup(
            JDMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        jMenu1.setBackground(new java.awt.Color(153, 255, 153));
        jMenu1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jMenu1.setText(" Producto ");
        jMenu1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText(" Detalle de Compra ");
        jMenu2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText(" Compra ");
        jMenu3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMIGesttionCompras.setText("Gestion De Compras");
        jMIGesttionCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGesttionComprasActionPerformed(evt);
            }
        });
        jMenu3.add(jMIGesttionCompras);

        jMICompraxprov.setText("Seleccionar Compra por proveedor");
        jMICompraxprov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMICompraxprovMouseClicked(evt);
            }
        });
        jMICompraxprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICompraxprovActionPerformed(evt);
            }
        });
        jMenu3.add(jMICompraxprov);

        jMICompraxFecha.setText("Seleccionar Compra por fecha");
        jMICompraxFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICompraxFechaActionPerformed(evt);
            }
        });
        jMenu3.add(jMICompraxFecha);

        jMenuBar1.add(jMenu3);

        jMenu4.setText(" Proveedor ");
        jMenu4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu5.setText(" Salir ");
        jMenu5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDMenu)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMICompraxprovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMICompraxprovMouseClicked
       JDMenu.removeAll();
       JDMenu.repaint();
     //  ComprasxProveedor cpp= new ComprasxProveedor();
     //  cpp.setVisible(true);
      // JDMenu.add(cpp);
      // JDMenu.moveToFront(cpp);
              
    }//GEN-LAST:event_jMICompraxprovMouseClicked

    private void jMIGesttionComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGesttionComprasActionPerformed
       JDMenu.removeAll();
       JDMenu.repaint();
      Compras cmp= new Compras();
       cmp.setVisible(true);
       JDMenu.add(cmp);
       JDMenu.moveToFront(cmp);
              
    }//GEN-LAST:event_jMIGesttionComprasActionPerformed

    private void jMICompraxprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICompraxprovActionPerformed
       JDMenu.removeAll();
       JDMenu.repaint();
     // ComprasxProveedor cpp= new ComprasxProveedor();
      // cpp.setVisible(true);
      // JDMenu.add(cpp);
      // JDMenu.moveToFront(cpp);  
    }//GEN-LAST:event_jMICompraxprovActionPerformed

    private void jMICompraxFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICompraxFechaActionPerformed
        JDMenu.removeAll();
       JDMenu.repaint();
    //   ComprasXFecha cpf= new ComprasXFecha();
     //  cpf.setVisible(true);
     //  JDMenu.add(cpf);
     //  JDMenu.moveToFront(cpf);  
    }//GEN-LAST:event_jMICompraxFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDMenu;
    private javax.swing.JMenuItem jMICompraxFecha;
    private javax.swing.JMenuItem jMICompraxprov;
    private javax.swing.JMenuItem jMIGesttionCompras;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
